package codigo;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

public class VentanaPrincipal extends javax.swing.JFrame {

    String[][] ejercicios =
            {
                {"array1", "makeMiddle","commonEnd","sum3","rotateLeft3","reverse3"
                ,"maxEnd3","sum2","middleWay","makeEnds","has23","no23","makeLast"
                ,"double23","fix23","start1","biggerTwo"},

                {"array2","countEvens","bigDiff","centeredAverage","sum13","sum67"
                ,"has22","lucky13","sum28","more14","fizzArray","only14","fizzArray2"
                ,"no14","isEverywhere","either24","matchUp","has77","has12"},
                
                {"array3","maxSpan","fix34","fix45","canBalance","linearIn"
                ,"squareUp","seriesUp","maxMirror","countClumps"},

                {"string1","helloName","makeAbba","makeTags","makeOutWord","extraEnd"
                ,"firstTwo","firstHalf","withoutEnd","comboString","nonStart","left2","right2"
                ,"theEnd","withouEnd2","middleTwo"},

                {"string2","doubleChar","countHi","catDog","countCode","endOther"
                ,"xyzThere","bobThere","xyBalance","mixString","repeatEnd","repeatFront","repeatSeparator"}
            }
    ;	 	 
 	 	  	 
         
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setSize(1400, 600);
        JButton boton ;

        System.out.print(ejercicios.length);
        for (int i=0; i< ejercicios.length; i++){
            JPanel jPanel1 = new JPanel();
            jPanel1.setSize(1400, 100);
            jPanel1.setLocation(0, i*100);
            jPanel1.setLayout(new GridLayout(0,9));
            boton = new JButton();
            boton.setText(ejercicios[i][0]);
            boton.setFocusPainted(false);
            boton.setBackground(Color.orange);
            jPanel1.add(boton);
            for (int j=1; j< ejercicios[i].length; j++){
                boton = new JButton();
                 boton.setText(ejercicios[i][j]);
                 boton.setFocusPainted(false);
                 jPanel1.add(boton); 
            }
            getContentPane().add(jPanel1);
        }
        
  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
